const express = require('express');
const router = express.Router();
const WhatsAppService = require('../services/whatsapp-evolution.service');
router.post('/config', (req, res) => { try { const { serverUrl, apiKey, instanceName } = req.body; WhatsAppService.setConfig(serverUrl, apiKey, instanceName); res.json({ sucesso: true }); } catch (e) { res.status(500).json({ erro: e.message }); } });
router.get('/config', (req, res) => { res.json({ serverUrl: WhatsAppService.config.serverUrl || '', apiKey: WhatsAppService.config.apiKey ? '***' : '', instanceName: WhatsAppService.config.instanceName || 'ubmax' }); });
router.post('/criar-instancia', async (req, res) => { try { const r = await WhatsAppService.criarInstancia(); res.json(r); } catch (e) { res.status(500).json({ erro: e.message }); } });
router.get('/conectar', async (req, res) => { try { const r = await WhatsAppService.conectar(); res.json(r); } catch (e) { res.status(500).json({ erro: e.message }); } });
router.get('/status', async (req, res) => { try { const r = await WhatsAppService.getStatus(); res.json(r); } catch (e) { res.status(500).json({ erro: e.message }); } });
router.post('/desconectar', async (req, res) => { try { const r = await WhatsAppService.desconectar(); res.json(r); } catch (e) { res.status(500).json({ erro: e.message }); } });
router.post('/teste', async (req, res) => { try { const { telefone, mensagem } = req.body; const r = await WhatsAppService.enviarTexto(telefone, mensagem || 'Teste UBMAX!'); res.json(r); } catch (e) { res.status(500).json({ erro: e.message }); } });
router.post('/enviar', async (req, res) => { try { const { telefone, mensagem } = req.body; const r = await WhatsAppService.enviarTexto(telefone, mensagem); res.json(r); } catch (e) { res.status(500).json({ erro: e.message }); } });
module.exports = router;
